; main.den
; File generated by Traductor de Gustavo Padilla
	name main
	.model small
	.data
presioneparasalir db 0ah,0dh,"Presione para salir...$"
ypremain dw 0
xpremain dw 0
amain dd 0.0
bmain dw 0
pmain dw 0
qmain dw 0
Yes0 db 0ah,0dh,"Y-es-0$"
Ynoes0 db 0ah,0dh,"Y-no-es-0$"
Xquizasiguesiendo0omenor db 0ah,0dh,"X-quiza-sigue-siendo-0-o-menor$"
Xyanoesmenorque0 db 0ah,0dh,"X-ya-no-es-menor-que-0$"
Holamundo db 0ah,0dh,"Hola-mundo$"
	.code
premain:
	mov xpremain,0
	mov ypremain,0
	zkvtrbvd:
	mov ax,xpremain
	mov bx,0
	cmp ax,bx
	jnbe endwhilehezxgiwd
	mov ax,ypremain
	mov bx,0
	cmp ax,bx
	jne endifbctesnaa
	lea dx,Yes0
	mov ah,9
	int 21h
	mov ax,1
	add ax,ypremain
	mov ypremain,ax
	jmp zkvtrbvd
	nolabelncvxtqav:
	jmp nolabeljxlccvad
	endifbctesnaa:
	lea dx,Ynoes0
	mov ah,9
	int 21h
	mov ax,1
	add ax,xpremain
	mov xpremain,ax
	nolabeljxlccvad:
	nolabelohmbirjj:
	endelsecamwhrba:
	lea dx,Xquizasiguesiendo0omenor
	mov ah,9
	int 21h
	endwhilehezxgiwd:
	lea dx,Xyanoesmenorque0
	mov ah,9
	int 21h
	ret
main:
	mov ax,5
	add ax,5
	mov pmain,ax
	lea dx,Holamundo
	mov ah,9
	int 21h
	jmp premain
	ret
start:
	mov ax,@data
	mov ds,ax
	jmp main
	lea dx,presioneparasalir
	mov ah,9
	int 21h
	mov ax,4c00h
	int 21h
	ret
end start

