; main.den
; File generated by Traductor de Gustavo Padilla
	name main
	.model small
	.data
presioneparasalir db 0ah,0dh,"Presione para salir...$"
y dw 0
x dw 0
a dd 0.0
b dw 0
p dw 0
q dw 0
Esverdad db 0ah,0dh,"Es-verdad$"
Esmentira db 0ah,0dh,"Es-mentira$"
Holamundo db 0ah,0dh,"Hola-mundo$"
	.code
premain:
	mov x,0
	mov y,0
	mov ax,x
	mov bx,0
	cmp ax,bx
	jnb endifvzsrectv
	lea dx,Esverdad
	mov ah,9
	int 21h
	jmp endelseajhfcfyn
	endifvzsrectv:
	lea dx,Esmentira
	mov ah,9
	int 21h
	endelseajhfcfyn:
	ret
main:
	mov p,5
	lea dx,Holamundo
	mov ah,9
	int 21h
	jmp premain
	ret
start:
	mov ax,@data
	mov ds,ax
	jmp main
	lea dx,presioneparasalir
	mov ax,4c00h
	int 21h
	ret
end start

