; while.den
; File generated by Traductor de Gustavo Padilla
	name while
	.model small
	.data
presioneparasalir db 0ah,0dh,"Presione para salir...$"
imain dw 0
i db 0ah,0dh,"$"
	.code
main:
	mov imain,1
	cvlhrnbi:
	mov ax,imain
	mov bx,10
	cmp ax,bx
	jnb endwhilempsgrmno
	add imain,30h
	lea dx,imain
	mov ah,9
	int 21h
	sub imain,30h
	mov ax,2
	imul imain
	mov imain,ax
	jmp cvlhrnbi
	nolabeldlrbbctx:
	endwhilempsgrmno:
	jmp start
start:
	mov ax,@data
	mov ds,ax
	jmp main
	lea dx,presioneparasalir
	mov ah,9
	int 21h
	mov ax,4c00h
	int 21h
	ret
end start

