; main.den
; File generated by Traductor de Gustavo Padilla
	name main
	model small
	.data
Hola-mundo db 0ah,0dh,"Hola-mundo$"
	.code
mov ax @data
mov ds,ax @data
premain:
main:
	lea dx,Hola-mundo
	mov ah,9
	int 21h
